mod apple_format;
mod audio;
mod audio_ducking;
mod cache;
pub mod commands;
pub mod config;
pub mod dictation;
mod formatting;
pub mod history;
mod hotkey;
mod local_whisper;
mod log;
pub mod model_manager;
pub mod ollama;
mod paste;
mod sidecar;
mod speech;
mod transcription;
mod vad;
#[cfg(target_os = "windows")]
mod win_overlay;
